server:
  port: 8889   # Default port for Config Server

spring:
  application:
    name: central-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Mintbeast7/Centralize-Config-Server.git   # üîÅ Your config repo
          default-label: main                                                     # branch name
          clone-on-start: true                                                    # clone at startup
          search-paths: microservices-demo                        # folder inside repo (optional)
